# Generated by Django 3.2.25 on 2026-05-15 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0001_initial'),
        ('mallas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('producto', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('en_cola', 'En Cola BarTender'), ('enviado', 'Enviado a BarTender'), ('error_api', 'Error API'), ('completado', 'Completado')], default='generado', max_length=20)),
                ('orden_envio', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio_bt', models.DateTimeField(blank=True, null=True)),
                ('bartender_resp', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('malla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='mallas.mallalogistica')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ['orden_envio'],
            },
        ),
    ]
