# Generated by Django 3.2.25 on 2026-05-17 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('numero_bolsa', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('escaneada', 'Escaneada')], default='pendiente', max_length=20)),
                ('fecha_escaneo', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='lotes.lote')),
            ],
            options={
                'ordering': ['numero_bolsa'],
            },
        ),
    ]
