# Generated by Django 3.2.25 on 2026-05-17 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_bolsa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolsa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={},
        ),
        migrations.RemoveField(
            model_name='bolsa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='bolsa',
            name='fecha_escaneo',
        ),
        migrations.RemoveField(
            model_name='bolsa',
            name='numero_bolsa',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='malla',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='orden',
        ),
        migrations.AddField(
            model_name='bolsa',
            name='codigo_bolsa',
            field=models.CharField(default='TEMP-0001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolsa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolsa',
            name='impresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='serial',
            field=models.CharField(default='TEMP-SERIAL', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='codigo_barras',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='bartender_resp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='codigo_lote',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('generado', 'Generado'), ('enviado', 'Enviado'), ('error_api', 'Error API'), ('completado', 'Completado')], default='generado', max_length=20),
        ),
        migrations.AlterField(
            model_name='lote',
            name='orden_envio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lote',
            name='producto',
            field=models.CharField(max_length=120),
        ),
    ]
