# Generated by Django 3.2.25 on 2026-05-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_auto_20260516_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='codigo_bolsa',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='serial',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='lote',
            name='codigo_lote',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
