# Generated by Django 3.2.25 on 2026-05-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_auto_20260516_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='ruta',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='sede',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='codigo_barras',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='codigo_bolsa',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='serial',
            field=models.CharField(max_length=120),
        ),
    ]
