# Generated by Django 3.2.25 on 2026-05-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0005_auto_20260516_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='destinatario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='ciudad',
            field=models.CharField(default='Sin ciudad', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='ruta',
            field=models.CharField(default='Sin ruta', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bolsa',
            name='sede',
            field=models.CharField(default='Sin sede', max_length=150),
            preserve_default=False,
        ),
    ]
