# Generated by Django 3.2.25 on 2026-05-18 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0006_auto_20260516_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='escaneada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='escaneada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bolsas_escaneadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='fecha_escaneo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
