# Generated by Django 3.2.25 on 2026-05-18 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lotes', '0007_auto_20260517_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=120)),
                ('sede', models.CharField(max_length=150)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bolsa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas', to='lotes.bolsa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='lotes.lote')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
