# Generated by Django 3.2.25 on 2026-05-15 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MallaLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='mallas/')),
                ('formato', models.CharField(choices=[('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=10)),
                ('fecha_distribucion', models.DateField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('archivada', 'Archivada'), ('procesando', 'Procesando')], default='procesando', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('total_sedes', models.IntegerField(default=0)),
                ('total_unidades', models.IntegerField(default=0)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('ruta', models.CharField(blank=True, max_length=100)),
                ('cuota_asignada', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='mallas.mallalogistica')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
