# Generated by Django 3.2.25 on 2026-05-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='ciudad',
            new_name='municipio',
        ),
        migrations.AddField(
            model_name='sede',
            name='aps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='bolsas_cerdo_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='bolsas_cerdo_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='bolsas_pollo_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='bolsas_pollo_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='bolsas_pollo_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='bolsas_res',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sede',
            name='institucion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sede',
            name='peso_total_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
